#!/bin/bash

# =====================================================
# Quick start script for Komodo CD with Docker
# =====================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║                                                          ║${NC}"
echo -e "${BLUE}║           🦎  Komodo CD - Docker Setup                  ║${NC}"
echo -e "${BLUE}║                                                          ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""

# Check Docker is installed
if ! command -v docker &> /dev/null; then
    echo -e "${RED}❌ Docker is not installed${NC}"
    exit 1
fi

if ! command -v docker compose &> /dev/null && ! docker-compose --version &> /dev/null; then
    echo -e "${RED}❌ Docker Compose is not installed${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Docker and Docker Compose detected${NC}"
echo ""

# =====================================================
# Generate secrets with OpenSSL
# =====================================================

echo -e "${YELLOW}🔐 Generating secrets with OpenSSL...${NC}"

BETTER_AUTH_SECRET=$(openssl rand -base64 32)
SEED_ADMIN_PASSWORD=$(openssl rand -base64 16)

echo -e "${GREEN}✅ Secrets generated${NC}"
echo ""

# =====================================================
# Configure environment variables
# =====================================================

echo -e "${YELLOW}⚙️  Configuring environment...${NC}"
echo ""

# Ask for APP_URL
read -rp "🌐 Public app URL (e.g., https://deploy.yourdomain.com): " APP_URL

# Validate URL
if [ -z "$APP_URL" ]; then
    echo -e "${RED}❌ URL is required${NC}"
    exit 1
fi

# Remove trailing slash if present
APP_URL=$(echo "$APP_URL" | sed 's:/*$::')

# Ask for port (optional)
read -rp "📍 Host port to expose the app [80]: " PORT
PORT=${PORT:-80}

# Ask for admin email (optional)
read -rp "👤 Admin email [admin@example.com]: " SEED_ADMIN_EMAIL
SEED_ADMIN_EMAIL=${SEED_ADMIN_EMAIL:-admin@example.com}

# Ask for admin name (optional)
read -rp "👤 Admin name [Admin]: " SEED_ADMIN_NAME
SEED_ADMIN_NAME=${SEED_ADMIN_NAME:-Admin}

echo ""

# =====================================================
# Create .env file
# =====================================================

cat > .env << EOF
# ─── Public app URL ───────────────────────────────────────────────────────────
# Without trailing slash. Used for CORS, trusted origins, and curl snippets.
APP_URL=$APP_URL

# Port that Nginx exposes on the host (default 80)
PORT=$PORT

# ─── Better Auth ──────────────────────────────────────────────────────────────
# Secret key for signing sessions and tokens.
# Automatically generated by the script.
BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET

# ─── Initial admin ────────────────────────────────────────────────────────────
# Automatically created the first time the backend starts.
SEED_ADMIN_EMAIL=$SEED_ADMIN_EMAIL
SEED_ADMIN_NAME=$SEED_ADMIN_NAME
SEED_ADMIN_PASSWORD=$SEED_ADMIN_PASSWORD
EOF

echo -e "${GREEN}✅ .env file created${NC}"
echo ""

# =====================================================
# Show summary
# =====================================================

echo -e "${BLUE}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║                    📋 CONFIGURATION                       ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  🌐 Public URL:      ${GREEN}$APP_URL${NC}"
echo -e "  📍 Port:            ${GREEN}$PORT${NC}"
echo -e "  👤 Admin email:     ${GREEN}$SEED_ADMIN_EMAIL${NC}"
echo -e "  👤 Admin name:      ${GREEN}$SEED_ADMIN_NAME${NC}"
echo -e "  🔑 Admin password:  ${GREEN}$SEED_ADMIN_PASSWORD${NC}"
echo ""
echo -e "  ${YELLOW}⚠️  Save this password, it's only shown once${NC}"
echo ""

# =====================================================
# Start Docker Compose
# =====================================================

echo -e "${YELLOW}🚀 Starting Docker Compose...${NC}"
echo ""

if command -v docker compose &> /dev/null; then
    docker compose up -d
else
    docker-compose up -d
fi

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║                  ✅ ALL SET!                              ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  🌐 Application available at: ${GREEN}$APP_URL${NC}"
echo -e "  📊 Komodo dashboard:         ${GREEN}$APP_URL${NC}"
echo ""
echo -e "  👤 Login:"
echo -e "     Email:    ${GREEN}$SEED_ADMIN_EMAIL${NC}"
echo -e "     Password: ${GREEN}$SEED_ADMIN_PASSWORD${NC}"
echo ""
echo -e "  ${BLUE}Useful commands:${NC}"
echo -e "     View logs:          ${YELLOW}docker compose logs -f${NC}"
echo -e "     Restart:            ${YELLOW}docker compose restart${NC}"
echo -e "     Stop:               ${YELLOW}docker compose down${NC}"
echo -e "     Update:             ${YELLOW}docker compose pull && docker compose up -d${NC}"
echo ""
